site:
  title: Roman Dobrynin â€” CV
  url: https://rdobrynin.github.io
  start_page: cv::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      exclude:
        - README.adoc
        - README.md

ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true

output:
  dir: build/site
