site:
  title: Roman Dobrynin â€” CV
  url: https://rdobrynin.github.io
  start_page: cv::index.adoc

content:
  sources:
    - url: .
      branches: HEAD

ui:
  bundle:
    url: ./ui-bundle
    snapshot: true

output:
  dir: build/site
