site:
  title: Roman Dobrynin â€” CV
  url: https://rdobrynin.github.io
  start_page: en::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_paths:
        - en
        - ru

ui:
  bundle:
    url: ./ui-bundle
    snapshot: true

output:
  dir: build/site
